const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const IMAGE_DIR = path.join(ROOT, 'database', 'seed', 'species_images');
const UPLOADED_PATH = path.join(IMAGE_DIR, 'final_species_image_assets_uploaded.json');
const ASSETS_PATH = path.join(IMAGE_DIR, 'final_species_image_assets.json');
const SQL_PATH = path.join(IMAGE_DIR, 'update_species_images.sql');

function readAssets(inputPath) {
  return JSON.parse(fs.readFileSync(inputPath, 'utf8'));
}

function hasPublicUrl(asset) {
  return Boolean(asset.public_url && String(asset.public_url).trim());
}

function chooseInput() {
  if (fs.existsSync(UPLOADED_PATH)) {
    const uploadedAssets = readAssets(UPLOADED_PATH);
    const publicUrlCount = uploadedAssets.filter(hasPublicUrl).length;

    if (publicUrlCount > 0) {
      return { inputPath: UPLOADED_PATH, assets: uploadedAssets, publicUrlCount };
    }
  }

  const assets = readAssets(ASSETS_PATH);
  return {
    inputPath: ASSETS_PATH,
    assets,
    publicUrlCount: assets.filter(hasPublicUrl).length,
  };
}

function sqlString(value) {
  if (!value) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function main() {
  const { inputPath, assets, publicUrlCount } = chooseInput();
  const readyRows = assets.filter(hasPublicUrl);
  const skippedRows = assets.length - readyRows.length;
  const relativeInputPath = path.relative(ROOT, inputPath).replace(/\\/g, '/');

  const lines = [
    '-- Fishy species image import SQL',
    '-- Generated by scripts/species_images/generate_update_species_images_sql.js',
    `-- Generated timestamp: ${new Date().toISOString()}`,
    '-- WARNING: review this SQL before running it. Do not run it until image URLs and WHERE clauses are manually checked.',
    '-- This file performs UPDATE only; no schema changes and no deletes.',
    `-- Input file: ${relativeInputPath}`,
    `-- Total update count: ${readyRows.length}`,
    `-- Rows with public_url: ${publicUrlCount}`,
    `-- Rows skipped without public_url: ${skippedRows}`,
    '',
  ];

  if (readyRows.length === 0) {
    lines.push('-- No executable UPDATE statements were generated because no asset row has a real public_url yet.');
    lines.push('-- Upload local files first, then rerun this generator.');
  } else {
    for (const asset of readyRows) {
      lines.push(`-- ${asset.species_key} | ${asset.common_name}`);
      lines.push('UPDATE fish_species');
      lines.push('SET');
      lines.push(`  image_url = ${sqlString(asset.public_url)},`);
      lines.push(`  thumbnail_url = ${sqlString(asset.public_url)},`);
      lines.push(`  image_license = ${sqlString(asset.image_license)},`);
      lines.push(`  image_source_url = ${sqlString(asset.image_source_url)}`);
      lines.push(`WHERE common_name = ${sqlString(asset.common_name)} AND entry_type = ${sqlString(asset.entry_type)};`);
      lines.push('');
    }
  }

  fs.writeFileSync(SQL_PATH, lines.join('\n') + '\n');
  console.log(JSON.stringify({
    input: path.basename(inputPath),
    inputPath: relativeInputPath,
    publicUrlCount,
    updateStatements: readyRows.length,
    skippedRows,
  }, null, 2));
}

main();
