BEGIN;

-- Section A-F: Malaysia ornamental livebearer library batch 1.
INSERT INTO fish_species (
  common_name, scientific_name, entry_type, category_id, family, water_type, origin,
  adult_size_min_cm, adult_size_max_cm, lifespan_min_years, lifespan_max_years,
  temperament, diet, care_level, temperature_min_c, temperature_max_c, ph_min, ph_max,
  hardness_min_dgh, hardness_max_dgh, minimum_tank_size_liters, tank_level,
  schooling_behavior, description, care_notes, feeding_notes, compatibility_notes,
  avoid_with_notes, image_url, thumbnail_url, image_license, image_source_url,
  verification_status, confidence_level, last_reviewed_at, local_availability
)
SELECT
  v.common_name, v.scientific_name, v.entry_type, v.category_id, v.family, v.water_type::water_type, v.origin,
  v.adult_size_min_cm, v.adult_size_max_cm, v.lifespan_min_years, v.lifespan_max_years,
  v.temperament::temperament, v.diet::diet_type, v.care_level::care_level,
  v.temperature_min_c, v.temperature_max_c, v.ph_min, v.ph_max,
  v.hardness_min_dgh, v.hardness_max_dgh, v.minimum_tank_size_liters, v.tank_level,
  v.schooling_behavior, v.description, v.care_notes, v.feeding_notes, v.compatibility_notes,
  v.avoid_with_notes, v.image_url, v.thumbnail_url, v.image_license, v.image_source_url,
  v.verification_status::verification_status, v.confidence_level::confidence_level,
  v.last_reviewed_at::timestamptz, v.local_availability
FROM (VALUES
  ('Common Guppy', 'Poecilia reticulata', 'species', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'South America (Trinidad, Venezuela, Guyana); widely naturalized in Asia including Malaysia', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'One of the most popular and widely kept aquarium fish worldwide. Hardy and easy to breed. Males are smaller and more colourful than females.', 'Very adaptable and tolerant of a wide range of water conditions. Excellent beginner fish. Avoid aggressive fin-nippers.', 'Accepts most dried foods, live and frozen daphnia, brine shrimp, bloodworm.', 'Peaceful with other small community fish.', 'Aggressive fin-nippers, large predatory fish', NULL, NULL, NULL, NULL, 'verified', 'high', '2025-01-01', 'common'),
  ('Endler''s Livebearer', 'Poecilia wingei', 'species', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Venezuela (Laguna de Patos and nearby localities)', 2, 3.5, 1, 3, 'peaceful', 'omnivore', 'beginner', 24, 28, 7.0, 8.5, 10, 20, 30, 'Middle to top', true, 'Tiny, brilliantly coloured livebearer closely related to the guppy. Wild populations are critically endangered.', 'Can hybridize with guppies if kept together; keep species pure to preserve bloodlines. Very active.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Full Red Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Solid red body and fins; one of the most popular show strains in Malaysia.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'common'),
  ('Albino Full Red Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Albino form of the Full Red strain with pink/red eyes and reduced pigmentation.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('24K Gold Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Deep golden-yellow metallic body with yellow or matching tail.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Blue Grass Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Fine grass-like blue pattern across the tail fin; bred for delicate patterning.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Red Grass Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Grass-like red patterning across the caudal fin.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Moscow Blue Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Iridescent blue-purple body with full blue tail; originated in Russia.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'common'),
  ('Moscow Black Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Deep black body colouration; one of the darker Moscow strains.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Japan Blue Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Distinctive iridescent blue on the rear body and tail; developed in Japan.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Tuxedo Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Dark black anterior half contrasting with a colourful rear and tail.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'common'),
  ('Half Black Red Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Half black body with red tail; classic show strain.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Red Dragon Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Dragon scale-like metallic red/orange pattern over the body.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'common'),
  ('Dumbo Ear Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Enlarged pectoral fins resembling ears; also called Elephant Ear Guppy.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Koi Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Koi-like orange, black and white patterning across the body and tail.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'common'),
  ('Snakeskin Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Rosette-like snake scale pattern across the body; associated with specific lace genes.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Metal Head Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Distinctive metallic iridescent head colouration.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Platinum White Guppy', 'Poecilia reticulata', 'strain', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species native to South America', 3, 6, 1, 3, 'peaceful', 'omnivore', 'beginner', 22, 28, 6.8, 7.8, 8, 20, 40, 'Middle to top', true, 'Near-white or platinum metallic body with minimal pattern.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Black Molly', 'Poecilia sphenops', 'variety', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species from Central America', 6, 10, 2, 5, 'peaceful', 'omnivore', 'beginner', 24, 28, 7.0, 8.5, 10, 25, 75, 'Middle', false, 'All-black colour variety of the Short-finned Molly. Hardy and peaceful.', 'Tolerates slightly brackish water. Algae grazer. Can be kept in small groups.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'common'),
  ('Sailfin Molly', 'Poecilia latipinna', 'species', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'North America (Atlantic and Gulf coastal plains)', 8, 12, 3, 5, 'peaceful', 'omnivore', 'beginner', 22, 28, 7.0, 8.5, 10, 30, 110, 'Middle', false, 'Impressive large dorsal fin in males. Naturally found in coastal and brackish waters.', 'Benefits from a small addition of aquarium salt. Needs space due to adult size.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'verified', 'high', '2025-01-01', 'common'),
  ('Giant Sailfin Molly', 'Poecilia velifera', 'species', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Yucatan Peninsula, Mexico', 10, 18, 3, 5, 'peaceful', 'omnivore', 'intermediate', 24, 28, 7.0, 8.5, 10, 30, 200, 'Middle', false, 'The largest of the sailfin mollies. Males have an enormous dorsal fin. Requires a large tank.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Balloon Molly', 'Poecilia sphenops', 'variety', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species from Central America', 5, 8, 2, 4, 'peaceful', 'omnivore', 'intermediate', 24, 28, 7.0, 8.5, 10, 25, 75, 'Middle', false, 'Rounded, compressed body caused by a selective breed mutation. Available in many colour varieties.', 'The body shape may predispose to swim bladder and organ compression issues. Avoid overfeeding.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'common'),
  ('Dalmatian Molly', 'Poecilia latipinna', 'variety', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species from North America (Atlantic and Gulf coastal plains)', 8, 12, 3, 5, 'peaceful', 'omnivore', 'beginner', 22, 28, 7.0, 8.5, 10, 30, 110, 'Middle', false, 'Black-spotted white body pattern resembling a Dalmatian dog.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'common'),
  ('Lyretail Molly', 'Poecilia sphenops', 'variety', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species from Central America', 6, 10, 2, 5, 'peaceful', 'omnivore', 'beginner', 24, 28, 7.0, 8.5, 10, 25, 75, 'Middle', false, 'Lyre-shaped caudal fin. Available in multiple colour forms.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Golden Molly', 'Poecilia sphenops', 'variety', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species from Central America', 6, 10, 2, 5, 'peaceful', 'omnivore', 'beginner', 24, 28, 7.0, 8.5, 10, 25, 75, 'Middle', false, 'Yellow-gold colour variety of the Short-finned Molly.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Platy', 'Xiphophorus maculatus', 'species', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Mexico, Guatemala, Belize', 4, 6, 3, 5, 'peaceful', 'omnivore', 'beginner', 18, 28, 7.0, 8.5, 10, 25, 60, 'Middle', false, 'Robust and colourful livebearer available in many colour varieties. Excellent community fish.', 'Very hardy. One of the most recommended beginner fish. Tolerates a wide temperature range.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'common'),
  ('Variatus Platy', 'Xiphophorus variatus', 'species', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Mexico (southern Tamaulipas to northern Veracruz)', 4, 7, 3, 5, 'peaceful', 'omnivore', 'beginner', 15, 25, 7.0, 8.0, 10, 25, 60, 'Middle', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Mickey Mouse Platy', 'Xiphophorus maculatus', 'variety', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species from Mexico, Guatemala, Belize', 4, 6, 3, 5, 'peaceful', 'omnivore', 'beginner', 18, 28, 7.0, 8.5, 10, 25, 60, 'Middle', false, 'Three dark spots at the base of the tail resemble Mickey Mouse silhouette.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'common'),
  ('Sunset Platy', 'Xiphophorus maculatus', 'variety', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species from Mexico, Guatemala, Belize', 4, 6, 3, 5, 'peaceful', 'omnivore', 'beginner', 18, 28, 7.0, 8.5, 10, 25, 60, 'Middle', false, 'Yellow to orange gradient body fading to a darker tail; popular colour variety.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'common'),
  ('Coral Red Platy', 'Xiphophorus maculatus', 'variety', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species from Mexico, Guatemala, Belize', 4, 6, 3, 5, 'peaceful', 'omnivore', 'beginner', 18, 28, 7.0, 8.5, 10, 25, 60, 'Middle', false, 'Deep coral to red body colouration; one of the most vivid platy varieties.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Swordtail', 'Xiphophorus hellerii', 'species', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Mexico and Central America', 8, 12, 3, 5, 'semi_aggressive', 'omnivore', 'beginner', 18, 27, 7.0, 8.3, 12, 30, 110, 'Middle', false, 'Males have a characteristic elongated lower tail fin forming a sword shape. Active and bold.', 'Males may chase other males. Keep more females than males. Active swimmer, needs length.', NULL, NULL, 'Do not keep multiple males in small tanks', NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'common'),
  ('Red Swordtail', 'Xiphophorus hellerii', 'variety', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species from Mexico and Central America', 8, 12, 3, 5, 'semi_aggressive', 'omnivore', 'beginner', 18, 27, 7.0, 8.3, 12, 30, 110, 'Middle', false, 'Solid red body with red sword tail; one of the most common ornamental swordtail colours.', NULL, NULL, NULL, 'Do not keep multiple males in small tanks', NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'common'),
  ('Pineapple Swordtail', 'Xiphophorus hellerii', 'variety', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred; base species from Mexico and Central America', 8, 12, 3, 5, 'semi_aggressive', 'omnivore', 'beginner', 18, 27, 7.0, 8.3, 12, 30, 110, 'Middle', false, 'Yellow-green body with red and black edging on the fins.', NULL, NULL, NULL, 'Do not keep multiple males in small tanks', NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate'),
  ('Hi-fin Swordtail', 'Xiphophorus hellerii', 'variety', (SELECT id FROM fish_categories WHERE slug = 'livebearer'), 'Poeciliidae', 'freshwater', 'Selectively bred for an elongated dorsal fin; base species from Mexico and Central America', 8, 12, 3, 5, 'semi_aggressive', 'omnivore', 'beginner', 18, 27, 7.0, 8.3, 12, 30, 110, 'Middle', false, 'Selectively bred for an elongated dorsal fin in addition to the sword tail.', NULL, NULL, NULL, 'Do not keep multiple males in small tanks', NULL, NULL, NULL, NULL, 'partially_verified', 'medium', '2025-01-01', 'moderate')
) AS v (
  common_name, scientific_name, entry_type, category_id, family, water_type, origin,
  adult_size_min_cm, adult_size_max_cm, lifespan_min_years, lifespan_max_years,
  temperament, diet, care_level, temperature_min_c, temperature_max_c, ph_min, ph_max,
  hardness_min_dgh, hardness_max_dgh, minimum_tank_size_liters, tank_level,
  schooling_behavior, description, care_notes, feeding_notes, compatibility_notes,
  avoid_with_notes, image_url, thumbnail_url, image_license, image_source_url,
  verification_status, confidence_level, last_reviewed_at, local_availability
)
WHERE NOT EXISTS (
  SELECT 1 FROM fish_species existing
  WHERE existing.common_name = v.common_name
    AND existing.entry_type = v.entry_type
);

-- Section G: Source rows.
INSERT INTO fish_species_sources (species_id, source_name, source_url, source_type, fields_supported, notes, retrieved_at)
SELECT id, 'FishBase', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', 'scientific_database',
ARRAY['scientific_name','water_type','origin','adult_size_min_cm','adult_size_max_cm','temperature_min_c','temperature_max_c','ph_min','ph_max','diet'], NULL, '2025-01-01'
FROM fish_species WHERE common_name = 'Common Guppy' AND entry_type = 'species'
ON CONFLICT (species_id, source_name) DO NOTHING;

INSERT INTO fish_species_sources (species_id, source_name, source_url, source_type, fields_supported, notes, retrieved_at)
SELECT id, 'Seriously Fish', 'https://www.seriouslyfish.com/species/poecilia-reticulata/', 'care_guide',
ARRAY['care_level','care_notes','feeding_notes','compatibility_notes','minimum_tank_size_liters','temperament'], NULL, '2025-01-01'
FROM fish_species WHERE common_name = 'Common Guppy' AND entry_type = 'species'
ON CONFLICT (species_id, source_name) DO NOTHING;

INSERT INTO fish_species_sources (species_id, source_name, source_url, source_type, fields_supported, notes, retrieved_at)
SELECT id, 'FishBase', 'https://www.fishbase.se/summary/Poecilia-wingei.html', 'scientific_database',
ARRAY['scientific_name','water_type','origin','adult_size_min_cm','adult_size_max_cm','temperature_min_c','temperature_max_c','ph_min','ph_max'], NULL, '2025-01-01'
FROM fish_species WHERE common_name = 'Endler''s Livebearer' AND entry_type = 'species'
ON CONFLICT (species_id, source_name) DO NOTHING;

INSERT INTO fish_species_sources (species_id, source_name, source_url, source_type, fields_supported, notes, retrieved_at)
SELECT fs.id, 'FishBase', s.source_url, 'scientific_database', s.fields_supported, s.notes, '2025-01-01'
FROM fish_species fs
JOIN (VALUES
  ('Full Red Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Albino Full Red Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('24K Gold Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Blue Grass Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Red Grass Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Moscow Blue Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Moscow Black Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Japan Blue Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Tuxedo Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Half Black Red Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Red Dragon Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Dumbo Ear Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Koi Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Snakeskin Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Metal Head Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Platinum White Guppy', 'strain', 'https://www.fishbase.se/summary/Poecilia-reticulata.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Water parameters inherited from base species Poecilia reticulata'),
  ('Black Molly', 'variety', 'https://www.fishbase.se/summary/Poecilia-sphenops.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Parameters inherited from base species Poecilia sphenops'),
  ('Giant Sailfin Molly', 'species', 'https://www.fishbase.se/summary/Poecilia-velifera.html', ARRAY['scientific_name','water_type','origin','adult_size_min_cm','adult_size_max_cm','temperature_min_c','temperature_max_c','ph_min','ph_max'], NULL),
  ('Balloon Molly', 'variety', 'https://www.fishbase.se/summary/Poecilia-sphenops.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Parameters inherited from base species Poecilia sphenops'),
  ('Dalmatian Molly', 'variety', 'https://www.fishbase.se/summary/Poecilia-latipinna.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Parameters inherited from base species Poecilia latipinna'),
  ('Lyretail Molly', 'variety', 'https://www.fishbase.se/summary/Poecilia-sphenops.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Parameters inherited from base species Poecilia sphenops'),
  ('Golden Molly', 'variety', 'https://www.fishbase.se/summary/Poecilia-sphenops.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Parameters inherited from base species Poecilia sphenops'),
  ('Platy', 'species', 'https://www.fishbase.se/summary/Xiphophorus-maculatus.html', ARRAY['scientific_name','water_type','origin','adult_size_min_cm','adult_size_max_cm','temperature_min_c','temperature_max_c','ph_min','ph_max'], NULL),
  ('Variatus Platy', 'species', 'https://www.fishbase.se/summary/Xiphophorus-variatus.html', ARRAY['scientific_name','water_type','origin','adult_size_min_cm','adult_size_max_cm','temperature_min_c','temperature_max_c','ph_min','ph_max'], NULL),
  ('Mickey Mouse Platy', 'variety', 'https://www.fishbase.se/summary/Xiphophorus-maculatus.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Parameters inherited from base species Xiphophorus maculatus'),
  ('Sunset Platy', 'variety', 'https://www.fishbase.se/summary/Xiphophorus-maculatus.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Parameters inherited from base species Xiphophorus maculatus'),
  ('Coral Red Platy', 'variety', 'https://www.fishbase.se/summary/Xiphophorus-maculatus.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Parameters inherited from base species Xiphophorus maculatus'),
  ('Swordtail', 'species', 'https://www.fishbase.se/summary/Xiphophorus-hellerii.html', ARRAY['scientific_name','water_type','origin','adult_size_min_cm','adult_size_max_cm','temperature_min_c','temperature_max_c','ph_min','ph_max'], NULL),
  ('Red Swordtail', 'variety', 'https://www.fishbase.se/summary/Xiphophorus-hellerii.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Parameters inherited from base species Xiphophorus hellerii'),
  ('Pineapple Swordtail', 'variety', 'https://www.fishbase.se/summary/Xiphophorus-hellerii.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Parameters inherited from base species Xiphophorus hellerii'),
  ('Hi-fin Swordtail', 'variety', 'https://www.fishbase.se/summary/Xiphophorus-hellerii.html', ARRAY['scientific_name','water_type','temperature_min_c','temperature_max_c','ph_min','ph_max','adult_size_min_cm','adult_size_max_cm'], 'Parameters inherited from base species Xiphophorus hellerii')
) AS s(common_name, entry_type, source_url, fields_supported, notes)
  ON fs.common_name = s.common_name AND fs.entry_type = s.entry_type
ON CONFLICT (species_id, source_name) DO NOTHING;

INSERT INTO fish_species_sources (species_id, source_name, source_url, source_type, fields_supported, notes, retrieved_at)
SELECT id, 'FishBase', 'https://www.fishbase.se/summary/Poecilia-latipinna.html', 'scientific_database',
ARRAY['scientific_name','water_type','origin','adult_size_min_cm','adult_size_max_cm','temperature_min_c','temperature_max_c','ph_min','ph_max'], NULL, '2025-01-01'
FROM fish_species WHERE common_name = 'Sailfin Molly' AND entry_type = 'species'
ON CONFLICT (species_id, source_name) DO NOTHING;

INSERT INTO fish_species_sources (species_id, source_name, source_url, source_type, fields_supported, notes, retrieved_at)
SELECT id, 'Seriously Fish', 'https://www.seriouslyfish.com/species/poecilia-latipinna/', 'care_guide',
ARRAY['care_level','care_notes','minimum_tank_size_liters','temperament'], NULL, '2025-01-01'
FROM fish_species WHERE common_name = 'Sailfin Molly' AND entry_type = 'species'
ON CONFLICT (species_id, source_name) DO NOTHING;

COMMIT;
